##### 1.Sayılardan oluşan bir boyutlu array oluşturun. Arrayi oluştururken sayıların veri tipini integer olarak belirtelim.

Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.

In [1]:
import numpy as np

In [2]:
x=np.array([7,28,12,2,29,6],dtype="int")

In [7]:
np.ndim(x)

1

In [8]:
np.size(x)

6

##### 2. Aşağıda verilen iki boyutlu ve üç boyutlu arrayi oluşturalım. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşalım. 

İki boyutlu array:
[[1,2,6,7],
 [4,3,9,5]]

Üç boyutlu array:
[[[7,5,14],[21,8,11]],
 [[8,6,20],[14,3,9]]]

 

In [20]:
arry2 = np.array([[1,2,6,7],[4,3,9,5]])
arry3 = np.array([[[7,5,14],[21,8,11]],[[8,6,20],[14,3,9]]])

In [21]:
arry2

array([[1, 2, 6, 7],
       [4, 3, 9, 5]])

In [22]:
arry3

array([[[ 7,  5, 14],
        [21,  8, 11]],

       [[ 8,  6, 20],
        [14,  3,  9]]])

In [23]:
np.ndim(arry2)


2

In [24]:
np.ndim(arry3)

3

In [25]:
np.size(arry2)

8

In [26]:
np.size(arry3)

12

In [27]:
np.shape(arry2)

(2, 4)

In [28]:
np.shape(arry3)

(2, 2, 3)

##### 3. İstenilen elamanlara ulaşmak için arrayler üzerinde indexleme işlemi yapalım

In [30]:
#İki boyutlu arraydaki 2 elemanına ulaşalım
arry2[0,1]

2

In [31]:
#İki boyutlu arraydaki 7 elemanına ulaşalım,
arry2[0,3]

7

In [32]:
#Üç boyutlu arraydaki 9 elemanına ulaşalım
arry3[1,1,2]

9

In [33]:
#Üç boyutlu arraydaki 5 elemanına ulaşalım
arry3[0,0,1]

5

##### 4. Arrayler üzerinde slicing işlemi uygulayalım.

In [34]:
arry2

array([[1, 2, 6, 7],
       [4, 3, 9, 5]])

In [35]:
arry3

array([[[ 7,  5, 14],
        [21,  8, 11]],

       [[ 8,  6, 20],
        [14,  3,  9]]])

In [37]:
#İki boyutlu arraydaki 2,6 elemanlarına ulaşalım
arry2[0:1,1:3]

array([[2, 6]])

In [38]:
#İki boyutlu arraydaki 3,9,5 elemanlarına ulaşalım
arry2[1,1:]

array([3, 9, 5])

In [39]:
#Üç boyutlu arraydaki 21,8,11 elemanlarına ulaşalım
arry3[0,1,:]

array([21,  8, 11])

In [40]:
#Üç boyutlu arraydaki 6,20 elemanlarına ulaşalım
arry3[1,0,1:]

array([ 6, 20])

##### 5. 5 satır 3 sütunluk sıfırlardan ve birlerden oluşan iki tane iki boyutlu array oluşturalım. Bu arrayleri satır ve sütun bazında birleştirelim.

In [43]:
s=np.zeros((5,3),dtype="int")
s

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [45]:
b= np.ones((5,3),dtype="int")
b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [49]:
satir = np.concatenate([s,b])
satir

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [50]:
sutun = np.concatenate([s,b],axis=1)
sutun

array([[0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1]])